import Head from 'next/head';

import { SpellCheckTestView } from '@src/components/view';

const SpellCheckTestPage = () => {
  return (
    <div>
      <Head>
        <title>IELTS Practice APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SpellCheckTestView />
      </main>
    </div>
  );
};

export default SpellCheckTestPage;
